import { LabelSmall } from '../Typography/Headlines&Texts';

export const BADGES_CONFIG = {
  status: {
    active: {
      icon: 'status-green-round',
      bgColor: '#E9FDF0',
      borderColor: '#C5E4CB',
      color: '#16A34A',
      title: 'Active',
      iconSize: 6,
      textComponent: LabelSmall,
    },
    paused: {
      icon: 'status-yellow-round',
      bgColor: '#FFFBEB',
      borderColor: '#FDE68A',
      color: '#D97706',
      title: 'Paused',
      iconSize: 6,
      textComponent: LabelSmall,
    },
    archived: {
      icon: 'status-gray-round',
      bgColor: '#F0F0F0',
      borderColor: '#C8C8CB',
      color: '#3E4655',
      title: 'Archived',
      iconSize: 6,
      textComponent: LabelSmall,
    },
    blocked: {
      icon: 'status-red-round',
      bgColor: '#FDEBEC',
      borderColor: '#FFD9D9',
      color: '#DC2626',
      title: 'Blocked',
      iconSize: 6,
      textComponent: LabelSmall,
    },
    completed: {
      icon: 'status-blue-round',
      bgColor: '#EAF3FF',
      borderColor: '#AAC5F9',
      color: '#0066CC',
      title: 'Completed',
      iconSize: 6,
      textComponent: LabelSmall,
    },
  },
  roles: {
    admin: {
      bgColor: '#EAF3FF',
      borderColor: '#AAC5F9',
      color: '#0066CC',
      title: 'Admin',
      textComponent: LabelSmall,
    },
    headOfTeam: {
      bgColor: '#F4EFFE',
      borderColor: '#D1C4E8',
      color: '#7C3AED',
      title: 'Head of Team',
      textComponent: LabelSmall,
    },
    teamLead: {
      bgColor: '#E9FDF0',
      borderColor: '#C5E4CB',
      color: '#16A34A',
      title: 'Team Lead',
      textComponent: LabelSmall,
    },
    buyer: {
      bgColor: '#F4FFFF',
      borderColor: '#B6E4E3',
      color: '#00C5C5',
      title: 'Buyer',
      textComponent: LabelSmall,
    },
    viewer: {
      bgColor: '#F0F0F0',
      borderColor: '#C8C8CB',
      color: '#3E4655',
      title: 'Viewer',
      textComponent: LabelSmall,
    },
    prostateHealth: {
      bgColor: '#FAFAFA',
      borderColor: '#D3DDE7',
      color: '#64748B',
      title: 'Prostate Health',
      textComponent: LabelSmall,
    },
  },
  tokenStatus: {
    tokenValid: {
      icon: 'green-clock',
      bgColor: '#E9FDF0',
      borderColor: '#C5E4CB',
      color: '#16A34A',
      title: 'Token Valid',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    tokenExpiringSoon: {
      icon: 'yellow-clock',
      bgColor: '#FFFBEB',
      borderColor: '#FDE68A',
      color: '#D97706',
      title: 'Token Expiring Soon',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    tokenExpired: {
      icon: 'red-clock',
      bgColor: '#FDEBEC',
      borderColor: '#FFD9D9',
      color: '#DC2626',
      title: 'Token Expired',
      iconSize: 16,
      textComponent: LabelSmall,
    },
  },
  badges: {
    error: {
      icon: 'badge-error',
      borderColor: '#E4E4E7',
      color: '#D97706',
      title: 'Error',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    partnerAdded: {
      icon: 'badge-partner',
      borderColor: '#E4E4E7',
      color: '#09090B',
      title: 'Partner Added',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    login: {
      icon: 'badge-login',
      borderColor: '#E4E4E7',
      color: '#09090B',
      title: 'Login',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    offerUpdated: {
      icon: 'badge-offer-updated',
      borderColor: '#E4E4E7',
      color: '#09090B',
      title: 'Offer Updated',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    success: {
      icon: 'icon-success',
      borderColor: '#E4E4E7',
      color: '#16A34A',
      title: 'Success',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    registration: {
      icon: 'badge-offer-updated',
      borderColor: '#E4E4E7',
      color: '#09090B',
      title: 'Registration',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    registrationBlue: {
      icon: 'badge-registration',
      borderColor: '#E4E4E7',
      color: '#0066CC',
      title: 'Registration',
      iconSize: 16,
      textComponent: LabelSmall,
    },
    system: {
      icon: 'black-clock',
      borderColor: '#E4E4E7',
      color: '#09090B',
      title: 'System',
      iconSize: 16,
      textComponent: LabelSmall,
    },
  },
};
